project:
  type: book

book:
  chapters:
    # Secciones Preliminares (sin numerar)
    - index.qmd              # Prefacio
    - prologo.qmd            # Prólogo
    - resumen.qmd            # Resumen
    - agradecimientos.qmd    # Agradecimientos
    - autor.qmd              # Acerca del Autor
    
    # Capítulos Principales (numerados)
    - intro.qmd              # Capítulo 1: Introducción
    - retos.qmd              # Capítulo 2: Retos
    - soluciones.qmd         # Capítulo 3: Soluciones
    
    # Apéndices y Referencias (sin numerar)
    - glosario.qmd           # Glosario
    - references.qmd         # Referencias

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    include-in-header:
      - text: |
          \usepackage{pdfpages}
    include-before-body:
      - text: |
          \includepdf[pages=-, noautoscale=true, width=\paperwidth, height=\paperheight]{photos/portada2.png}



