project:
  type: book

book:
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - agradecimientos.qmd
    - about.qmd
    - references.qmd
    - retos.qmd
    - soluciones.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    include-in-header:
      - text: |
          \usepackage{pdfpages}
    include-before-body:
      - text: |
          \includepdf[pages=-, noautoscale=true, width=\paperwidth, height=\paperheight]{photos/portada2.png}



